### ISSUE TITLE
Can only open sheets for monsters from the basic rules

### ISSUE THREAD

**Issue by 9Volt1** [zeel01/MonsterBlocks#203]
After importing from DndBeyond using Mr Primate's ddbImporter, I am only able to open npc sheets for monsters from the basic rules or those I've created.  Monsters from any other source, such as the MM or Volo's do not open when I click on them in the compendium, actors tab, or on the map.  Disabling Monster blocks allows me to access all sheets normally

**Comment by zeel01** [comment]
Are there errors in the console when you try to open these actors? What version of Foundry and of dnd5e are you using? Could you attach the exported JSON of an effected actor?

**Comment by 9Volt1** [comment]
Foundry Version 10.291
5e Version 2.1.2

Console:
foundry.js:747 TypeError: Cannot read properties of undefined (reading 'cha')
[Detected 2 packages: monsterblock, system:dnd5e]
    at CastingPreper.getCastingAbility (CastingPreper.js:566:43)
    at CastingPreper.prepare (CastingPreper.js:129:51)
    at ItemPrep.prepareItem (ItemPrep.js:103:12)
[fvtt-Actor-pixie.zip](https://github.com/zeel01/MonsterBlocks/files/10451777/fvtt-Actor-pixie.zip)

    at ItemPrep.organizeFeatures (ItemPrep.js:85:9)
    at ItemPrep.prepareItems (ItemPrep.js:62:8)
    at new ItemPrep (ItemPrep.js:36:8)
    at MonsterBlock5e._prepareItems (MonsterBlock5e.js:510:10)
    at MonsterBlock5e.getData (base-sheet.mjs:154:10)
    at MonsterBlock5e.getData (npc-sheet.mjs:27:33)
    at MonsterBlock5e.getData (MonsterBlock5e.js:66:28)
    at MonsterBlock5e._render (foundry.js:5108:29)
    at MonsterBlock5e._render (foundry.js:5822:17)
    at MonsterBlock5e.render (foundry.js:5067:10)
    at MonsterBlock5e.render (foundry.js:6394:18)
    at ActorDirectory._onClickDocumentName (foundry.js:60848:16)
    at HTMLOListElement.dispatch (jquery.min.js:2:43064)
    at y.handle (jquery.min.js:2:41048)

**Comment by 9Volt1** [comment]
Confirmed.  Thank you!  Do you have a patreon or the like?
