### ISSUE TITLE
Monster Blocks aren't showing up after selecting them as sheets

### ISSUE THREAD

**Issue by NomadODST** [zeel01/MonsterBlocks#231]
Im using dnd5e v3.1.2 on forge-vtt. after installing the module and setting them as default sheets for monsters none of the creatures open up anymore.

**Comment by BrianDEdwards** [comment]
I'm encountering the same issue with Foundry Version 11 and DnD5e 3.0.4. The following warning messages appear in the console when you switch the sheet type.

```
Error: You are accessing the Folder#data object which is no longer used. Since V10 the Document class and its contained DataModel are merged into a combined data structure. You should now reference keys which were previously contained within the data object directly.
    at logCompatibilityWarning (commons.js:2059:19)
    at Folder._logV10CompatibilityWarning (commons.js:8544:14)
    at get data [as data] (commons.js:8432:24)
    at AutoCompletionField._excluded (searchanywhere.js:671:29)
    at Object.fn (searchanywhere.js:554:26)
    at #call (foundry.js:730:20)
    at Hooks.callAll (foundry.js:687:17)
    at ClientDatabaseBackend.callback (foundry.js:13738:13)
    at foundry.js:13711:43
    at Array.map (<anonymous>)
    at #handleUpdateDocuments (foundry.js:13711:33)


Error: You are accessing Folder#parent which has been migrated to Folder#folder
Deprecated since Version 10
Backwards-compatible support will be removed in Version 12
    at logCompatibilityWarning (commons.js:2059:19)
    at Folder._logDataFieldMigration (commons.js:8533:14)
    at Object.get (commons.js:8497:18)
    at AutoCompletionField._excluded (searchanywhere.js:671:34)
    at Object.fn (searchanywhere.js:554:26)
    at #call (foundry.js:730:20)
    at Hooks.callAll (foundry.js:687:17)
    at ClientDatabaseBackend.callback (foundry.js:13738:13)
    at foundry.js:13711:43
    at Array.map (<anonymous>)
    at #handleUpdateDocuments (foundry.js:13711:33)


Error: You are accessing the Actor5e#data object which is no longer used. Since V10 the Document class and its contained DataModel are merged into a combined data structure. You should now reference keys which were previously contained within the data object directly.
    at logCompatibilityWarning (commons.js:2059:19)
    at Actor5e._logV10CompatibilityWarning (commons.js:8544:14)
    at get data [as data] (commons.js:8432:24)
    at safeGet (searchanywhere.js:360:22)
    at get content [as content] (searchanywhere.js:1045:37)
    at w.A (flexsearch.min.js:27:179)
    at w.update (flexsearch.min.js:28:18)
    at Object.fn (searchanywhere.js:555:32)
    at #call (foundry.js:730:20)
    at Hooks.callAll (foundry.js:687:17)
    at ClientDatabaseBackend.callback (foundry.js:13738:13)
    at foundry.js:13711:43
    at Array.map (<anonymous>)
    at #handleUpdateDocuments (foundry.js:13711:33)
```

And the following error message appears in the console when you attempt to open a sheet that is set to use Monster Blocks

```
Uncaught (in promise) TypeError: undefined. Cannot convert undefined or null to object
[Detected 2 packages: monsterblock, system:dnd5e]
    at Function.entries (<anonymous>)
    at MonsterBlock5e.getTraitChecklist (MonsterBlock5e.js:394:10)
    at MonsterBlock5e.prepDamageTypeMenu (MonsterBlock5e.js:347:8)
    at MonsterBlock5e.prepAttributeMenu (MonsterBlock5e.js:297:21)
    at MonsterBlock5e.prepMenus (MonsterBlock5e.js:220:21)
    at new MonsterBlock5e (MonsterBlock5e.js:31:8)
    at get sheet [as sheet] (foundry.js:14122:23)
    at TokenDocument5e._onUpdateBaseActor (foundry.js:25250:18)
    at Actor5e._updateDependentTokens (foundry.js:19205:13)
    at Actor5e._onUpdate (foundry.js:19140:10)
    at Actor5e._onUpdate (document.mjs:98:11)
    at Actor5e._onUpdate (actor.mjs:3091:11)
    at ClientDatabaseBackend.callback (foundry.js:13737:11)
    at foundry.js:13711:43
    at Array.map (<anonymous>)
    at #handleUpdateDocuments (foundry.js:13711:33)
```

**Comment by jazzman831** [comment]
@zeel01 I'm not OP, but I can confirm sheets are now opening on DnDe v3.3.1

**Comment by NomadODST** [comment]
![Image](https://github.com/user-attachments/assets/5ba3add2-1e91-4494-9226-22c43d276977)

the error i get. so i seem to have an issue on my side
